{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-flux-webhook-autoreconciler
spec:
  ingress:
    - from:
        - namespaceSelector: {}
  podSelector:
    matchLabels:
      {{- include "flux-webhook-autoreconciler.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
{{- end }}