apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "flux-webhook-autoreconciler.fullname" . }}
  labels:
    {{- include "flux-webhook-autoreconciler.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - source.toolkit.fluxcd.io
    resources:
      - ocirepositories
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "flux-webhook-autoreconciler.fullname" . }}
  labels:
    {{- include "flux-webhook-autoreconciler.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name:  {{ include "flux-webhook-autoreconciler.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "flux-webhook-autoreconciler.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
